// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/api/login.ts";
import * as $3 from "./routes/api/logout.ts";
import * as $4 from "./routes/api/oauth.ts";
import * as $5 from "./routes/api/signup.ts";
import * as $6 from "./routes/api/subscription.ts";
import * as $7 from "./routes/blog/[slug].tsx";
import * as $8 from "./routes/blog/index.tsx";
import * as $9 from "./routes/dashboard/_middleware.ts";
import * as $10 from "./routes/dashboard/account.tsx";
import * as $11 from "./routes/dashboard/api/hashtag.ts";
import * as $12 from "./routes/dashboard/api/todo.ts";
import * as $13 from "./routes/dashboard/hashtags.tsx";
import * as $14 from "./routes/dashboard/index.tsx";
import * as $15 from "./routes/dashboard/manage-subscription.ts";
import * as $16 from "./routes/dashboard/todos.tsx";
import * as $17 from "./routes/dashboard/upgrade-subscription.ts";
import * as $18 from "./routes/feed.ts";
import * as $19 from "./routes/index.tsx";
import * as $20 from "./routes/login/index.tsx";
import * as $21 from "./routes/login/success.tsx";
import * as $22 from "./routes/logout.ts";
import * as $23 from "./routes/signup.tsx";
import * as $$0 from "./islands/AuthFragmentCatcher.tsx";
import * as $$1 from "./islands/HashtagList.tsx";
import * as $$2 from "./islands/TodoList.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/api/login.ts": $2,
    "./routes/api/logout.ts": $3,
    "./routes/api/oauth.ts": $4,
    "./routes/api/signup.ts": $5,
    "./routes/api/subscription.ts": $6,
    "./routes/blog/[slug].tsx": $7,
    "./routes/blog/index.tsx": $8,
    "./routes/dashboard/_middleware.ts": $9,
    "./routes/dashboard/account.tsx": $10,
    "./routes/dashboard/api/hashtag.ts": $11,
    "./routes/dashboard/api/todo.ts": $12,
    "./routes/dashboard/hashtags.tsx": $13,
    "./routes/dashboard/index.tsx": $14,
    "./routes/dashboard/manage-subscription.ts": $15,
    "./routes/dashboard/todos.tsx": $16,
    "./routes/dashboard/upgrade-subscription.ts": $17,
    "./routes/feed.ts": $18,
    "./routes/index.tsx": $19,
    "./routes/login/index.tsx": $20,
    "./routes/login/success.tsx": $21,
    "./routes/logout.ts": $22,
    "./routes/signup.tsx": $23,
  },
  islands: {
    "./islands/AuthFragmentCatcher.tsx": $$0,
    "./islands/HashtagList.tsx": $$1,
    "./islands/TodoList.tsx": $$2,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
