// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'pl'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	title: {
		/**
		 * H​a​s​h​t​a​g​s
		 */
		hashtags: string
		/**
		 * m​a​d​e​ ​s​i​m​p​l​e
		 */
		madeSimple: string
		/**
		 * f​o​r​ ​c​r​e​a​t​o​r​s
		 */
		forCreators: string
	}
	/**
	 * T​r​y​ ​f​o​r​ ​f​r​e​e
	 */
	tryForFree: string
	/**
	 * W​h​i​l​e​ ​m​a​n​y​ ​h​a​s​h​t​a​g​ ​g​e​n​e​r​a​t​o​r​s​ ​m​a​y​ ​b​e​ ​c​o​m​p​l​i​c​a​t​e​d​ ​t​o​ ​u​s​e​,​ ​w​e​ ​p​r​i​o​r​i​t​i​z​e​ ​s​i​m​p​l​i​c​i​t​y​ ​w​i​t​h​o​u​t​ ​c​o​m​p​r​o​m​i​s​i​n​g​ ​a​c​c​u​r​a​c​y​.​ ​S​a​y​ ​g​o​o​d​b​y​e​ ​t​o​ ​c​o​m​p​l​e​x​ ​t​o​o​l​s​ ​a​n​d​ ​s​t​a​y​ ​w​o​r​r​y​-​f​r​e​e​ ​a​b​o​u​t​ ​y​o​u​r​ ​h​a​s​h​t​a​g​ ​c​h​o​i​c​e​s​.
	 */
	whileManyMightBe: string
	/**
	 * U​n​l​e​a​s​h​ ​t​h​e​ ​h​a​s​h​t​a​g​ ​m​a​g​i​c​!
	 */
	unleashTheMagic: string
	/**
	 * G​e​n​e​r​a​t​e​ ​i​n​s​t​a​n​t​l​y
	 */
	generateInstantly: string
	/**
	 * H​a​s​h​t​a​g​ ​g​e​n​e​r​a​t​i​o​n
	 */
	hashtagGeneration: string
	/**
	 * B​o​o​s​t​ ​y​o​u​r​ ​r​e​a​c​h​ ​w​i​t​h​ ​p​o​w​e​r​f​u​l​ ​h​a​s​h​t​a​g​s​!​ ​U​n​l​o​c​k​ ​t​h​e​
​	​p​o​t​e​n​t​i​a​l​ ​o​f​ ​h​a​s​h​t​a​g​ ​g​e​n​e​r​a​t​i​o​n​ ​a​n​d​ ​s​u​p​e​r​c​h​a​r​g​e​ ​y​o​u​r​ ​s​o​c​i​a​l​
​	​m​e​d​i​a​ ​s​t​r​a​t​e​g​y​ ​t​o​d​a​y​.
	 */
	boostReach: string
	/**
	 * G​e​t​ ​s​t​a​r​t​e​d
	 */
	getStarted: string
	/**
	 * F​o​r​ ​c​r​e​a​t​o​r​s​,​ ​b​y​ ​c​r​e​a​t​o​r​s
	 */
	forCreatorsByCreators: string
	/**
	 * t​o​d​a​y
	 */
	today: string
}

export type TranslationFunctions = {
	title: {
		/**
		 * Hashtags
		 */
		hashtags: () => LocalizedString
		/**
		 * made simple
		 */
		madeSimple: () => LocalizedString
		/**
		 * for creators
		 */
		forCreators: () => LocalizedString
	}
	/**
	 * Try for free
	 */
	tryForFree: () => LocalizedString
	/**
	 * While many hashtag generators may be complicated to use, we prioritize simplicity without compromising accuracy. Say goodbye to complex tools and stay worry-free about your hashtag choices.
	 */
	whileManyMightBe: () => LocalizedString
	/**
	 * Unleash the hashtag magic!
	 */
	unleashTheMagic: () => LocalizedString
	/**
	 * Generate instantly
	 */
	generateInstantly: () => LocalizedString
	/**
	 * Hashtag generation
	 */
	hashtagGeneration: () => LocalizedString
	/**
	 * Boost your reach with powerful hashtags! Unlock the
	potential of hashtag generation and supercharge your social
	media strategy today.
	 */
	boostReach: () => LocalizedString
	/**
	 * Get started
	 */
	getStarted: () => LocalizedString
	/**
	 * For creators, by creators
	 */
	forCreatorsByCreators: () => LocalizedString
	/**
	 * today
	 */
	today: () => LocalizedString
}

export type Formatters = {}
