import { type NextPage } from "next";
import Head from "next/head";
// import { useRouter } from "next/router";
import { SignInButton, UserButton, useClerk, useUser } from "@clerk/nextjs";
import { Button } from "~/components/Button";
import { IconLogin } from "@tabler/icons-react";
import { useEffect } from "react";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  // eslint-disable-next-line @typescript-eslint/unbound-method
  const { redirectToSignIn, session } = useClerk();
  const { user } = useUser();
  const router = useRouter();
  console.log("user", user);

  useEffect(() => {
    if (session) {
      void router.push({
        pathname: "/dashboard",
      });
    }
  }, [router, session]);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <h1 className="scroll-m-20 text-4xl font-extrabold tracking-tight lg:text-5xl">
          Hashbrown
        </h1>
        <Button
          className="max-w-sm gap-2"
          variant="ghost"
          onClick={() => void redirectToSignIn()}
        >
          Sign in <IconLogin />
        </Button>
      </main>
    </>
  );
};

export default Home;
